[env:esp32-poe2]
platform = espressif32
framework = arduino
board = esp32-poe
board_build.flash_mode = dio
board_build.partitions = esp32-4mb.csv
build_flags = 
	-D BOARD_HAS_PSRAM
	-D DEBUG
upload_speed = 921600
monitor_speed = 115200
lib_deps = 
	https://github.com/bblanchon/ArduinoJson
	https://github.com/me-no-dev/AsyncTCP
	https://github.com/me-no-dev/ESPAsyncWebServer
	https://github.com/marvinroger/async-mqtt-client
	https://github.com/miguelbalboa/rfid
	https://github.com/matjack1/Wiegand-Protocol-Library-for-Arduino
	https://github.com/PaulStoffregen/Time
	https://github.com/thomasfredericks/Bounce2
	https://github.com/tctlrd/Desfire
	https://github.com/miguelbalboa/rfid
	https://github.com/tctlrd/io2
	https://github.com/plerup/espsoftwareserial